major = 3
minor = 19
patch = 0
isAlpha = false
isBeta = true
isNodeProject = true
isDenoProject = false
[[remotes]]
name = "origin"
isPublic = true
group = "github"

[[remotes]]
name = "Fork"
group = "Mirrors"
provider = "github"
isPublic = true
branch = "master"
